server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://bkfopaxoffrqaw:b4ef26f8c14252a87e9ef4c5f452194c4251a0161b33073ebd22adca2ce4f2b6@ec2-34-232-191-133.compute-1.amazonaws.com:5432/d68v840q0qtv6p
    username: bkfopaxoffrqaw
    password: b4ef26f8c14252a87e9ef4c5f452194c4251a0161b33073ebd22adca2ce4f2b6
  jpa:
    show-sql: true
    database-plataform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  title: Projeto realizado para o bootcamp DIO - Santander
  description: Desenvolvido por Henrique Vieira Cavalcante
  version: 1.0
